import {
  AppNotification,
  Department,
  IssueComment,
  IssueEvent,
  IssueRecord,
  TeamMember,
} from "@/lib/types";

const now = new Date();

function hoursAgo(h: number): string {
  return new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
}

function hoursFromNow(h: number): string {
  return new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();
}

export const mockDepartments: Department[] = [
  { id: "dept_electricity", code: "ELEC", name: "Electricity Department" },
  { id: "dept_water", code: "WATER", name: "Water Supply Department" },
  { id: "dept_sanitation", code: "SAN", name: "Sanitation Department" },
  { id: "dept_public_works", code: "PWD", name: "Public Works Department" },
  { id: "dept_parks", code: "PARK", name: "Parks Department" },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: "u_super_1",
    fullName: "Anita Verma",
    email: "anita@nivaran.gov",
    role: "super_admin",
    departmentId: "dept_public_works",
    area: "city_wide",
    workload: 2,
    active: true,
  },
  {
    id: "u_head_elec",
    fullName: "Ajay Verma",
    email: "ajay@nivaran.gov",
    role: "department_head",
    departmentId: "dept_electricity",
    area: "area_ghaziabad",
    workload: 6,
    active: true,
  },
  {
    id: "u_head_water",
    fullName: "Ritika Sharma",
    email: "ritika@nivaran.gov",
    role: "department_head",
    departmentId: "dept_water",
    area: "area_ghaziabad",
    workload: 5,
    active: true,
  },
  {
    id: "u_head_san",
    fullName: "Suresh Yadav",
    email: "suresh@nivaran.gov",
    role: "department_head",
    departmentId: "dept_sanitation",
    area: "area_ghaziabad",
    workload: 7,
    active: true,
  },
  {
    id: "u_head_pwd",
    fullName: "Nidhi Bansal",
    email: "nidhi@nivaran.gov",
    role: "department_head",
    departmentId: "dept_public_works",
    area: "area_ghaziabad",
    workload: 4,
    active: true,
  },
  {
    id: "u_head_parks",
    fullName: "Kamal Mehta",
    email: "kamal@nivaran.gov",
    role: "department_head",
    departmentId: "dept_parks",
    area: "area_ghaziabad",
    workload: 3,
    active: true,
  },
  {
    id: "u_eng_1",
    fullName: "Maya Kulkarni",
    email: "maya@nivaran.gov",
    role: "engineer",
    departmentId: "dept_electricity",
    area: "area_ghaziabad",
    workload: 5,
    active: true,
  },
  {
    id: "u_eng_2",
    fullName: "Imran Khan",
    email: "imran@nivaran.gov",
    role: "engineer",
    departmentId: "dept_water",
    area: "area_ghaziabad",
    workload: 8,
    active: true,
  },
  {
    id: "u_eng_3",
    fullName: "Anuj Gupta",
    email: "anuj@nivaran.gov",
    role: "engineer",
    departmentId: "dept_sanitation",
    area: "area_ghaziabad",
    workload: 6,
    active: true,
  },
  {
    id: "u_eng_4",
    fullName: "Divya Rana",
    email: "divya@nivaran.gov",
    role: "engineer",
    departmentId: "dept_public_works",
    area: "area_ghaziabad",
    workload: 4,
    active: true,
  },
  {
    id: "u_eng_5",
    fullName: "Harsh Vohra",
    email: "harsh@nivaran.gov",
    role: "engineer",
    departmentId: "dept_parks",
    area: "area_ghaziabad",
    workload: 3,
    active: true,
  },
];

export const mockIssues: IssueRecord[] = [
  {
    id: "ISS-1001",
    title: "Street light not working near Sector 7",
    description: "Two street lights are off near the market road and visibility is low at night.",
    category: "Electricity & Power",
    urgency: "High",
    status: "In Progress",
    area: "area_ghaziabad",
    assignedDepartmentId: "dept_electricity",
    assignedToId: "u_eng_1",
    reporterName: "Vansh",
    username: "vansh",
    userId: "u_citizen_1",
    createdAt: hoursAgo(30),
    dueAt: hoursFromNow(8),
    lastStatusUpdateAt: hoursAgo(2),
    lastStatusUpdateBy: "Maya Kulkarni",
    affectedUsersCount: 17,
    affectedUserIds: ["u_citizen_1", "u_citizen_2", "u_citizen_3"],
    tags: ["streetlight", "night_safety"],
    upvotes: 16,
    downvotes: 1,
    commentsCount: 2,
    isUnresolved: true,
    assignedDepartment: "Electricity Department",
    voters: {
      u_citizen_1: "upvote",
      u_citizen_5: "upvote",
      u_citizen_9: "downvote",
    },
    imageUrl: "https://images.unsplash.com/photo-1521207418485-99c705420785?q=80&w=1200&auto=format&fit=crop",
    locationAddress: "Market Road, Ghaziabad",
    lat: 28.6692,
    lng: 77.4538,
  },
  {
    id: "ISS-1002",
    title: "Water leakage from main pipeline",
    description: "Water is leaking continuously near block C and road is flooded.",
    category: "Water Supply",
    urgency: "High",
    status: "Reported",
    area: "area_ghaziabad",
    assignedDepartmentId: "dept_water",
    reporterName: "Rahul",
    username: "rahul",
    userId: "u_citizen_4",
    createdAt: hoursAgo(6),
    dueAt: hoursFromNow(18),
    lastStatusUpdateAt: hoursAgo(4),
    lastStatusUpdateBy: "Ajay Verma",
    affectedUsersCount: 44,
    affectedUserIds: ["u_citizen_4", "u_citizen_10"],
    tags: ["pipeline", "water_loss"],
    upvotes: 33,
    downvotes: 0,
    commentsCount: 1,
    isUnresolved: true,
    assignedDepartment: "Water Supply Department",
    voters: {
      u_citizen_4: "upvote",
      u_citizen_10: "upvote",
    },
    imageUrl: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1200&auto=format&fit=crop",
    locationAddress: "Block C, Ghaziabad",
    lat: 28.6751,
    lng: 77.4499,
  },
  {
    id: "ISS-1003",
    title: "Garbage not collected for 3 days",
    description: "Waste pile has grown and causing foul smell near apartment gate.",
    category: "Sanitation",
    urgency: "Medium",
    status: "Acknowledged",
    area: "area_ghaziabad",
    assignedDepartmentId: "dept_sanitation",
    assignedToId: "u_eng_3",
    reporterName: "Priya",
    username: "priya",
    userId: "u_citizen_7",
    createdAt: hoursAgo(42),
    dueAt: hoursFromNow(20),
    lastStatusUpdateAt: hoursAgo(14),
    lastStatusUpdateBy: "Anuj Gupta",
    affectedUsersCount: 23,
    affectedUserIds: ["u_citizen_7", "u_citizen_11"],
    tags: ["garbage", "hygiene"],
    upvotes: 10,
    downvotes: 2,
    commentsCount: 3,
    isUnresolved: true,
    assignedDepartment: "Sanitation Department",
    voters: {
      u_citizen_7: "upvote",
      u_citizen_11: "upvote",
      u_citizen_12: "downvote",
    },
    imageUrl: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=1200&auto=format&fit=crop",
    locationAddress: "Lotus Residency Gate, Ghaziabad",
    lat: 28.6714,
    lng: 77.462,
  },
  {
    id: "ISS-1004",
    title: "Pothole in front of school",
    description: "Large pothole near school bus stop, risky during rain.",
    category: "Road Maintenance",
    urgency: "High",
    status: "Resolved",
    area: "area_ghaziabad",
    assignedDepartmentId: "dept_public_works",
    assignedToId: "u_eng_4",
    reporterName: "Neha",
    username: "neha",
    userId: "u_citizen_13",
    createdAt: hoursAgo(80),
    dueAt: hoursAgo(15),
    lastStatusUpdateAt: hoursAgo(12),
    lastStatusUpdateBy: "Divya Rana",
    affectedUsersCount: 31,
    affectedUserIds: ["u_citizen_13", "u_citizen_14"],
    tags: ["pothole", "school_zone"],
    upvotes: 21,
    downvotes: 1,
    commentsCount: 5,
    isUnresolved: false,
    assignedDepartment: "Public Works Department",
    voters: {
      u_citizen_13: "upvote",
      u_citizen_14: "upvote",
      u_citizen_15: "downvote",
    },
    imageUrl: "https://images.unsplash.com/photo-1520699049698-acd2fccb8cc8?q=80&w=1200&auto=format&fit=crop",
    locationAddress: "Shanti Public School, Ghaziabad",
    lat: 28.661,
    lng: 77.442,
  },
  {
    id: "ISS-1005",
    title: "Park lights flickering",
    description: "Lights in central park are flickering intermittently.",
    category: "Parks",
    urgency: "Low",
    status: "Rejected",
    area: "area_ghaziabad",
    assignedDepartmentId: "dept_parks",
    reporterName: "Karan",
    username: "karan",
    userId: "u_citizen_16",
    createdAt: hoursAgo(25),
    dueAt: hoursFromNow(35),
    lastStatusUpdateAt: hoursAgo(20),
    lastStatusUpdateBy: "System",
    affectedUsersCount: 6,
    affectedUserIds: ["u_citizen_16"],
    tags: ["park", "lighting"],
    upvotes: 3,
    downvotes: 6,
    commentsCount: 0,
    isUnresolved: false,
    assignedDepartment: "Parks Department",
    voters: {
      u_citizen_16: "downvote",
      u_citizen_17: "downvote",
    },
    imageUrl: "https://images.unsplash.com/photo-1470115636492-6d2b56f9146d?q=80&w=1200&auto=format&fit=crop",
    locationAddress: "Central Park, Ghaziabad",
    lat: 28.6643,
    lng: 77.4586,
  },
];

export const mockComments: IssueComment[] = [
  {
    id: "c-1",
    issueId: "ISS-1001",
    actorId: "u_head_elec",
    actorName: "Ajay Verma",
    text: "Field team dispatched to inspect the panel.",
    createdAt: hoursAgo(12),
  },
  {
    id: "c-2",
    issueId: "ISS-1002",
    actorId: "u_head_elec",
    actorName: "Ajay Verma",
    text: "Marked urgent due to water wastage and traffic blockage.",
    createdAt: hoursAgo(4),
  },
];

export const mockEvents: IssueEvent[] = [
  {
    id: "e-1",
    issueId: "ISS-1001",
    type: "created",
    title: "Issue reported",
    note: "Auto-classified by system",
    actorId: "system",
    actorName: "System",
    createdAt: hoursAgo(30),
  },
  {
    id: "e-2",
    issueId: "ISS-1001",
    type: "assignment",
    title: "Assigned to Maya Kulkarni",
    actorId: "u_head_elec",
    actorName: "Ajay Verma",
    createdAt: hoursAgo(20),
  },
  {
    id: "e-3",
    issueId: "ISS-1001",
    type: "status_change",
    title: "Status changed to In Progress",
    note: "Technician reached site",
    actorId: "u_eng_1",
    actorName: "Maya Kulkarni",
    createdAt: hoursAgo(10),
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: "n-1",
    userId: "u_eng_1",
    title: "New assignment",
    body: "ISS-1001 has been assigned to you.",
    isRead: false,
    createdAt: hoursAgo(20),
    issueId: "ISS-1001",
  },
  {
    id: "n-2",
    userId: "u_head_elec",
    title: "SLA warning",
    body: "ISS-1001 is approaching SLA deadline.",
    isRead: false,
    createdAt: hoursAgo(1),
    issueId: "ISS-1001",
  },
];
